[package]
name = "geobench"
version = "0.1.0"
authors = ["Julian Fondren"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maxminddb = "0.15.0"
